### PR TITLE
issue#22

### PR DESCRIPTION
**Pull request by dgarus**
Fix for
https://github.com/yegor256/rehttp/issues/22

### CODE REVIEW

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) please, pay attention to this pull request

**Comment by 0crat** [comment]
Job [#24](https://github.com/yegor256/rehttp/issues/24) is now in scope, role is `REV`

**Comment by 0crat** [comment]
@yegor256[/z](https://www.0crat.com/u/yegor256) everybody who has role `REV` is banned at [#24](https://github.com/yegor256/rehttp/issues/24); I won't be able to assign anyone automatically; consider assigning someone manually (as in [§19](http://www.zerocracy.com/policy.html#19)), or invite more people (as in [§51](http://www.zerocracy.com/policy.html#51)), or remove the job from the scope (as in [§14](http://www.zerocracy.com/policy.html#14))

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor merge

**Comment by yegor256** [comment]
@rultor release, tag is `0.7.3`

**Comment by yegor256** [comment]
@dgarus thanks!

**Comment by 0crat** [comment]
Job `gh:yegor256/rehttp#24` is not assigned, can't get performer

**Comment by 0crat** [comment]
The job [#24](https://github.com/yegor256/rehttp/issues/24) is now out of scope

**Comment by 0crat** [comment]
Payment to `ARC` for a closed pull request, as in [§28](http://www.zerocracy.com/policy.html#28): +10 point(s) just awarded to @yegor256[/z](https://www.0crat.com/u/yegor256)

**Comment by dgarus** [comment]
> @dgarus thanks!

You are welcome!

What should I do to close the issue #22?
Would it be closed automatically?

**Comment by dgarus** [comment]
@0crat status

**Comment by yegor256** [comment]
@dgarus I closed it

**Pull request merged**
